### PR TITLE
Switch from nosetests to pytest

### PR DESCRIPTION
**Pull request by h-vetinari**
While trying to verify that the GPU builds from https://github.com/conda-forge/scs-feedstock/pull/21 are working as intended (cf. this [comment](https://github.com/bodono/scs-python/issues/31#issuecomment-836808762)), I ran into a couple of problems;

The test suite is super noisy, it doesn't run with pytest (and nose is completely [dead](https://github.com/nose-devs/nose/)), and I couldn't tell if which flags had been picked up in `solve_random_cone_prob.py`.

I decided to refactor the test suite to be able to run with pytest, do some minimal parametrization (though much more could be done with those loops), turn `solve_random_cone_prob.py`. On the way, I fixed some (but not all) warnings, the remaining ones are:

<details>
<summary>Remaining warnings</summary>

```
================================================== warnings summary ===================================================
test/test_scs_python_linsys.py::test_python_linsys
  C:\Users\Axel\.conda\envs\test\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
    warn('splu requires CSC matrix format', SparseEfficiencyWarning)

test/test_scs_python_linsys.py::test_python_linsys
  C:\Users\Axel\Dev\conda-forge\upstreams\scs-python\test\test_scs_python_linsys.py:102: RuntimeWarning: Mean of empty slice.
    D[start:start+delta] = D[start:start+delta].mean()

test/test_scs_python_linsys.py::test_python_linsys
  C:\Users\Axel\.conda\envs\test\lib\site-packages\numpy\core\_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
    ret = ret.dtype.type(ret / rcount)
```

</details>

It also gave me a somewhat unclear answer whether the GPU builds work; the tests pass (though it should be said that currently, `test_solve_random_cone_prob.py` just tests whether the solver runs through, and not the results it produces), but the following (truncated) log is produced:

<details>
<summary>GPU warnings/errors</summary>

```
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu\gpu.c:12:scs__accum_by_atrans_gpu
 ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu/indirect\private.c:270:scs_init_lin_sys_work
ERROR_CUDA: an illegal memory access was encountered
scs/linsys/gpu/indirect\private.c:270:scs_init_lin_sys_work
ERROR_CUDA: an illegal memory access was encountered
```

</details>

I also adapted the ~4 year old https://github.com/bodono/scs-python/blob/master/test/scs_benchmarks.ipynb to be runnable again, but ran into https://github.com/cvxpy/cvxpy/issues/1369 & https://github.com/cvxpy/cvxpy/issues/1370.

The changes in total are quite a few, I'm happy to split this into smaller PRs if desired; the commits are "designed" to be reviewable independently though, and should be quite manageable.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Seems that travis isn't running anymore, you probably heard that the free version of travis was discontinued...

**Comment by bodono** [comment]
This is awesome, thanks for doing all this!

First, it runs fine for me and passes the tests, I don't see the GPU errors. What type of machine are you using?

**Comment by h-vetinari** [comment]
> 
> 
> This is awesome, thanks for doing all this!

Glad to hear it :)

> First, it runs fine for me and passes the tests, I don't see the GPU errors. What type of machine are you using?

As I mentioned, it doesn't error for me, but `pytest test -v` on a build installed with `--gpu` gives the log messages I copied. I believe they're coming from the C-Level, so that's probably why it doesn't immediately error the python tests.

My system is only a laptop with a GeForce MX150, but I have successfully run the test suites of other GPU-enabled libraries (e.g. faiss). There was only one test that failed then due to very large memory requirements.

**Comment by bodono** [comment]
Sorry, I meant that when I run this PR on my linux machine with a GPU and `_scs_gpu` successfully installed it passes all the tests. All I get are the `test_python_linsys ` warnings.

There are two possibilities I see for where that error is coming from. It's running on a system I wasn't able to test GPUs on after [the latest GPU code update](https://github.com/cvxgrp/scs/pull/155) (eg, Windows). Or somehow it's running out of GPU memory. Neither of those are caused by this PR though, so if you're comfortable with this change then we can get it submitted.

**Comment by bodono** [comment]
```
2021-05-15 12:27:46 (python37) 0 bodonoghue@bodonoghue-[]-~/git/scs-python:
└──[ins] => pytest test -v
===================================================================================================================================================================================== test session starts =====================================================================================================================================================================================
platform linux -- Python 3.7.3, pytest-6.2.3, py-1.10.0, pluggy-0.13.1 -- /usr/local/google/home/bodonoghue/miniconda2/envs/python37/bin/python
cachedir: .pytest_cache
rootdir: /usr/local/google/home/bodonoghue/git/scs-python
collected 27 items

test/test_scs_basic.py::test_problems[cone0-False-1] PASSED                                                                                                                                                                                                                                                                                                                             [  3%]
test/test_scs_basic.py::test_problems[cone1-True-1] PASSED                                                                                                                                                                                                                                                                                                                              [  7%]
test/test_scs_basic.py::test_problems[cone2-False-0.5] PASSED                                                                                                                                                                                                                                                                                                                           [ 11%]
test/test_scs_basic.py::test_problems[cone3-True-0.5] PASSED                                                                                                                                                                                                                                                                                                                            [ 14%]
test/test_scs_basic.py::test_failures PASSED                                                                                                                                                                                                                                                                                                                                            [ 18%]
test/test_scs_python_linsys.py::test_python_linsys PASSED                                                                                                                                                                                                                                                                                                                               [ 22%]
test/test_scs_rand.py::test_feasible[False] PASSED                                                                                                                                                                                                                                                                                                                                      [ 25%]
test/test_scs_rand.py::test_feasible[True] PASSED                                                                                                                                                                                                                                                                                                                                       [ 29%]
test/test_scs_rand.py::test_infeasible[False] PASSED                                                                                                                                                                                                                                                                                                                                    [ 33%]
test/test_scs_rand.py::test_infeasible[True] PASSED                                                                                                                                                                                                                                                                                                                                     [ 37%]
test/test_scs_rand.py::test_unbounded[False] PASSED                                                                                                                                                                                                                                                                                                                                     [ 40%]
test/test_scs_rand.py::test_unbounded[True] PASSED                                                                                                                                                                                                                                                                                                                                      [ 44%]
test/test_scs_sdp.py::test_feasible[False] PASSED                                                                                                                                                                                                                                                                                                                                       [ 48%]
test/test_scs_sdp.py::test_feasible[True] PASSED                                                                                                                                                                                                                                                                                                                                        [ 51%]
test/test_scs_sdp.py::test_infeasible[False] PASSED                                                                                                                                                                                                                                                                                                                                     [ 55%]
test/test_scs_sdp.py::test_infeasible[True] PASSED                                                                                                                                                                                                                                                                                                                                      [ 59%]
test/test_scs_sdp.py::test_unbounded[False] PASSED                                                                                                                                                                                                                                                                                                                                      [ 62%]
test/test_scs_sdp.py::test_unbounded[True] PASSED                                                                                                                                                                                                                                                                                                                                       [ 66%]
test/test_solve_random_cone_prob.py::test_solve_feasible[False-False] PASSED                                                                                                                                                                                                                                                                                                            [ 70%]
test/test_solve_random_cone_prob.py::test_solve_feasible[True-False] PASSED                                                                                                                                                                                                                                                                                                             [ 74%]
test/test_solve_random_cone_prob.py::test_solve_feasible[True-True] PASSED                                                                                                                                                                                                                                                                                                              [ 77%]
test/test_solve_random_cone_prob.py::test_solve_infeasible[False-False] PASSED                                                                                                                                                                                                                                                                                                          [ 81%]
test/test_solve_random_cone_prob.py::test_solve_infeasible[True-False] PASSED                                                                                                                                                                                                                                                                                                           [ 85%]
test/test_solve_random_cone_prob.py::test_solve_infeasible[True-True] PASSED                                                                                                                                                                                                                                                                                                            [ 88%]
test/test_solve_random_cone_prob.py::test_solve_unbounded[False-False] PASSED                                                                                                                                                                                                                                                                                                           [ 92%]
test/test_solve_random_cone_prob.py::test_solve_unbounded[True-False] PASSED                                                                                                                                                                                                                                                                                                            [ 96%]
test/test_solve_random_cone_prob.py::test_solve_unbounded[True-True] PASSED                                                                                                                                                                                                                                                                                                             [100%]

====================================================================================================================================================================================== warnings summary =======================================================================================================================================================================================
test/test_scs_python_linsys.py: 51 warnings
  /usr/local/google/home/bodonoghue/miniconda2/envs/python37/lib/python3.7/site-packages/scipy/sparse/linalg/dsolve/linsolve.py:296: SparseEfficiencyWarning: splu requires CSC matrix format
    warn('splu requires CSC matrix format', SparseEfficiencyWarning)

test/test_scs_python_linsys.py: 50 warnings
  /usr/local/google/home/bodonoghue/git/scs-python/test/test_scs_python_linsys.py:102: RuntimeWarning: Mean of empty slice.
    D[start:start+delta] = D[start:start+delta].mean()

test/test_scs_python_linsys.py: 50 warnings
  /usr/local/google/home/bodonoghue/miniconda2/envs/python37/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
    ret = ret.dtype.type(ret / rcount)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================================================================================================================================================================== 27 passed, 151 warnings in 21.79s ==============================================================================================================================================================================
```
And just to test that `_scs_gpu` imports sucessfully:
```
2021-05-15 12:28:09 (python37) 0 bodonoghue@bodonoghue-[]-~/git/scs-python:
└──[ins] => python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
└──[ins] >>> import _scs_gpu
└──[ins] >>> 
```

**Comment by h-vetinari** [comment]
> 
> 
> Sorry, I meant that when I run this PR on my linux machine with a GPU and `_scs_gpu` successfully installed it passes all the tests. All I get are the `test_python_linsys ` warnings.

Yeah, maybe I should have been clearer; this PR does not change the essence of the tests (except adding `solve_random_cone_prob.py`), but I wanted to use it precisely to verify the GPU-enabled builds from https://github.com/conda-forge/scs-feedstock/pull/21

> 
> There are two possibilities I see for where that error is coming from. It's running on a system I wasn't able to test GPUs on after [the latest GPU code update](https://github.com/cvxgrp/scs/pull/155) (eg, Windows). Or somehow it's running out of GPU memory. Neither of those are caused by this PR though, so if you're comfortable with this change then we can get it submitted.

It might be either or both of the former, but in any case, I agree that the PR is in mergable shape.

**Comment by h-vetinari** [comment]
> And just to test that `_scs_gpu` imports sucessfully:

I _can_ do this import successfully on windows as well; I'm just not sure what happens with the computation results, because `solve_random_cone_prob.py` doesn't do any checking of the outputs.

BTW, the 3 warnings are the same after a test-suite run on windows.

Finally, if you want to "test-drive" the binaries that would be produced by conda-forge, you can download the appropriate artefact (python & CUDA version) from [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=314426&view=artifacts&pathAsName=false&type=publishedArtifacts), unpack it somewhere & then do:
```
conda create -n test_env -c "/path/to/where/you/unpacked/the/artefact" scs python=<version>
```

You can find out the current version of your CUDA drivers by typing `conda info` and having a look under the `virtual packages` section.

**Comment by bodono** [comment]
Thanks again. I will update the tests so that they test numerical correctness next.

**Pull request merged**
