### PR TITLE
Add support for MKL pardiso in meson build.

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Review by bodono — APPROVED** [review]

**Comment by bodono** [comment]
Thanks for looking into this @isuruf !

This LGTM though I don't know much about meson. Pinging @enzbus who knows a lot more to see if he has any feedback.

**Comment by enzbus** [comment]
This looks great on the surface, but @bodono you are too kind I really just helped putting together the installation script and am far from an expert in this. I guess if it passes CI tests it's a go for me? Your call...

**Comment by enzbus** [comment]
@isuruf I see the removed anaconda hack in the meson.build and I approve, it was very tricky to get that to work, though

**Comment by bodono** [comment]
Ok LGTM, I _think_ @isuruf you can merge yourself now that I have approved? If not let me know and I can merge

**Comment by enzbus** [comment]
@bodono I have a hunch this patch broke windows wheels, I'm inspecting the test run logs. the "hack" was needed after all. I suggest you revert the merge

**Comment by isuruf** [comment]
Hmm, the run at https://github.com/bodono/scs-python/actions/runs/8926143160/job/24516515638 shows that it is being linked to openblas.

> The Meson build system
Version: 1.4.0
Source dir: C:\Users\runneradmin\AppData\Local\Temp\build-via-sdist-cale5a5x\scs-3.2.4
Build dir: C:\Users\runneradmin\AppData\Local\Temp\build-via-sdist-cale5a5x\scs-3.2.4\.mesonpy-j5y40ebb
Build type: native build
Project name: scs
Project version: undefined
C compiler for the host machine: gcc (gcc 12.2.0 "gcc (x86_64-posix-seh-rev2, Built by MinGW-W64 project) 12.2.0")
C linker for the host machine: gcc ld.bfd 2.39
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python found: YES (C:\Users\runneradmin\AppData\Local\Temp\build-env-gjpcqlz_\Scripts\python.exe)
Library openblas found: NO
Found pkg-config: YES (C:\Miniconda3\envs\test\Library\bin\pkg-config.EXE) 0.29.2
Run-time dependency openblas found: YES 0.3.27
Compiler for C supports arguments -Wno-unused-result: YES 
Run-time dependency python found: YES 3.12
Build targets in project: 2

**Comment by enzbus** [comment]
Sorry @isuruf , I may be wrong. I'm re-reading the GH yaml file and it should work, there's the explicit removal of conda openblas to make sure everything is linked statically, and there is a SDP problem in the testfiles. I'm concerned about this line (build 3.12, latest)
```
 Created wheel for scs: filename=scs-3.2.4-cp312-cp312-win_amd64.whl size=139833  ...
```
it should be around 10MB, but maybe it's before the delvewheel calll; GH removed logs from earlier runs so I can't compare...

**Comment by enzbus** [comment]
Ok, now I get it; you are installing `pkg-config` from conda and meson then is able to see openblas, makes sense. Thanks, @bodono I revert my reservations.

**Comment by bodono** [comment]
Thanks for looking into it @enzbus , I will leave as is then.

**Comment by enzbus** [comment]
Yes, it's a good MR @bodono , @isuruf improved the build a lot especially on Windows. I came across this project recently https://cibuildwheel.pypa.io , you probably already know it, I guess it would be a nice addition (not sure how difficult it is to use, we still need to customize the Windows build, install conda, ...)

**Pull request merged**
