### PR TITLE
Lazy import of numpy in setup.py

### PR DESCRIPTION
**Pull request by cHYzZQo**
Allows this package to bring it in as a dep instead of forcing it to be installed already.

### CODE REVIEW

**Comment by cHYzZQo** [comment]
Running locally I get the same test failures on master as travis shows on this branch. Are the failures a known issue? Or caused by the setup changes?

**Comment by cHYzZQo** [comment]
Hmm, that means that when i build master locally I'm also not linking in correctly. Does master work for you?

**Comment by bodono** [comment]
Master works for me, yes.

**Comment by cHYzZQo** [comment]
Got the tests to pass by moving the list settings down to the build_extension level.

**Comment by bodono** [comment]
Awesome, thanks!

**Comment by cHYzZQo** [comment]
Thanks for merging. Any idea when this will be available in pypi?

**Comment by bodono** [comment]
Up now.

**Pull request merged**
